/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Primitives;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Xablu.Petstore.Attributes;
using Xablu.Petstore.Models;
using Xablu.Petstore.Services;
using static Xablu.Petstore.Models.Pet;
using Newtonsoft.Json.Converters;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace Xablu.Petstore.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class PetApiController : Controller
    {
        private readonly IHostingEnvironment _environment;
        private readonly IPetService _petService;

        /// <summary>
        /// 
        /// </summary>
        public PetApiController(IHostingEnvironment environment, IPetService petService)
        {
            _environment = environment;
            _petService = petService;
        }

        /// <summary>
        /// Add a new pet to the store
        /// </summary>
        /// <remarks></remarks>
        /// <param name="body">Pet object that needs to be added to the store</param>
        /// <response code="405">Invalid input</response>
        [HttpPost]
        [Route("/v2/pet")]
        [ValidateModelState]
        [SwaggerOperation("AddPet")]
        public virtual Pet AddPet([FromBody]Pet body)
        {
            return _petService.AddPet(body);
        }

        /// <summary>
        /// Deletes a pet
        /// </summary>
        /// <remarks></remarks>
        /// <param name="petId">Pet id to delete</param>
        /// <param name="apiKey"></param>
        /// <response code="400">Invalid pet value</response>
        [HttpDelete]
        [Route("/v2/pet/{petId}")]
        [ValidateModelState]
        [SwaggerOperation("DeletePet")]
        public virtual IActionResult DeletePet([FromRoute]long? petId, [FromHeader]string apiKey)
        {
            if (_petService.DeletePet(petId)) return Ok();
            return NotFound();
        }

        /// <summary>
        /// Finds Pets by status
        /// </summary>
        /// <remarks>Multiple status values can be provided with comma separated strings</remarks>
        /// <param name="status">Status values that need to be considered for filter</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Invalid status value</response>
        [HttpGet]
        [Route("/v2/pet/findByStatus")]
        [ValidateModelState]
        [SwaggerOperation("FindPetsByStatus")]
        [SwaggerResponse(200, typeof(List<Pet>), "successful operation")]
        [SwaggerResponse(400, typeof(List<Pet>), "Invalid status value")]
        public virtual IActionResult FindPetsByStatus([FromQuery]List<string> status)
        {
            var searchStatus = new List<StatusEnum?>();
            foreach (var st in status)
            {
                if (st == "available") searchStatus.Add(StatusEnum.AvailableEnum);
                else if (st == "pending") searchStatus.Add(StatusEnum.PendingEnum);
                else if (st == "sold") searchStatus.Add(StatusEnum.SoldEnum);
                else return new BadRequestResult();
            }
            return new ObjectResult(_petService.FindPetsByStatus(searchStatus));
        }

        /// <summary>
        /// Finds Pets by tags
        /// </summary>
        /// <remarks>Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.</remarks>
        /// <param name="tags">Tags to filter by</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Invalid tag value</response>
        [HttpGet]
        [Route("/v2/pet/findByTags")]
        [ValidateModelState]
        [SwaggerOperation("FindPetsByTags")]
        [SwaggerResponse(200, typeof(List<Pet>), "successful operation")]
        [SwaggerResponse(400, typeof(List<Pet>), "Invalid tag value")]
        public virtual IActionResult FindPetsByTags([FromQuery]List<string> tags)
        {
            return new ObjectResult(_petService.FindPetsByTags(tags));
        }

        /// <summary>
        /// Find pet by ID
        /// </summary>
        /// <remarks>Returns a single pet</remarks>
        /// <param name="petId">ID of pet to return</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Invalid ID supplied</response>
        /// <response code="404">Pet not found</response>
        [HttpGet]
        [Route("/v2/pet/{petId}")]
        [ValidateModelState]
        [SwaggerOperation("GetPetById")]
        [SwaggerResponse(200, typeof(Pet), "successful operation")]
        [SwaggerResponse(400, typeof(Pet), "Invalid ID supplied")]
        [SwaggerResponse(404, typeof(Pet), "Pet not found")]
        public virtual IActionResult GetPetById([FromRoute]long? petId)
        {
            if (!petId.HasValue) return BadRequest();
            var pet = _petService.FindPetById(petId.Value);
            if (pet == null) return NotFound();
            return new ObjectResult(pet);
        }

        /// <summary>
        /// Update an existing pet
        /// </summary>
        /// <remarks></remarks>
        /// <param name="body">Pet object that needs to be added to the store</param>
        /// <response code="400">Invalid ID supplied</response>
        /// <response code="404">Pet not found</response>
        /// <response code="405">Validation exception</response>
        [HttpPut]
        [Route("/v2/pet")]
        [ValidateModelState]
        [SwaggerOperation("UpdatePet")]
        public virtual IActionResult UpdatePet([FromBody]Pet body)
        {
            if (!body.Id.HasValue) return BadRequest();
            var pet = _petService.FindPetById(body.Id.Value);
            if (pet == null) return NotFound();
            return new ObjectResult(_petService.UpdatePet(pet.Id.Value, body));
        }

        /// <summary>
        /// Updates a pet in the store with form data
        /// </summary>
        /// <remarks></remarks>
        /// <param name="petId">ID of pet that needs to be updated</param>
        /// <param name="name">Updated name of the pet</param>
        /// <param name="status">Updated status of the pet</param>
        /// <response code="405">Invalid input</response>
        [HttpPost]
        [Route("/v2/pet/{petId}")]
        [ValidateModelState]
        [SwaggerOperation("UpdatePetWithForm")]
        public virtual IActionResult UpdatePetWithForm([FromRoute]long? petId, [FromForm]string name, [FromForm]string status)
        {
            if (!petId.HasValue) return BadRequest();
            var pet = _petService.FindPetById(petId.Value);
            if (pet == null) return NotFound();

            StatusEnum petStatus;
            if (status == "available") petStatus = StatusEnum.AvailableEnum;
            else if (status == "pending") petStatus = StatusEnum.PendingEnum;
            else if (status == "sold") petStatus = StatusEnum.SoldEnum;
            else return StatusCode(405);

            return new ObjectResult(_petService.UpdatePet(pet.Id.Value, new Pet { Name = name, Status = petStatus }));
        }

        /// <summary>
        /// uploads an image
        /// </summary>
        /// <remarks></remarks>
        /// <param name="petId">ID of pet to update</param>
        /// <param name="additionalMetadata">Additional data to pass to server</param>
        /// <param name="file">file to upload</param>
        /// <response code="200">successful operation</response>
        [HttpPost]
        [Route("/v2/pet/{petId}/uploadImage")]
        [ValidateModelState]
        [SwaggerOperation("UploadFile")]
        [SwaggerResponse(200, typeof(ApiResponse), "successful operation")]
        public virtual async Task<IActionResult> UploadFile([FromRoute]long? petId, [FromForm]string additionalMetadata, [FromForm]IFormFile file)
        {
            if (!petId.HasValue) return BadRequest();
            var pet = _petService.FindPetById(petId.Value);
            if (pet == null) return NotFound();

            var imagePath = Path.Combine(_environment.ContentRootPath, "images", $"{petId.Value}", file.FileName);
            Directory.CreateDirectory(Path.GetDirectoryName(imagePath));

            using (var fileStream = new FileStream(imagePath, FileMode.Create))
            {
                await file.CopyToAsync(fileStream);
            }

            return Ok();
        }
    }
}
